POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de React Native"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/0bb74935-05f7-4247-b922-adc6ac9e648b

###
DELETE http://localhost:3333/courses/89b4c513-2f7e-403a-ae4a-2bd817316ce9